name: flutter_turismo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.7
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  # Para UI moderna
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  sign_in_with_apple: ^6.1.0
